### ISSUE TITLE
NodeCoreAudio/AudioEngine.cpp

### ISSUE THREAD

**Issue by dg14** [ZECTBynmo/node-core-audio#38]
under ubuntu-14.10 LTS (64bit) Sleep seems not exist...
(in NodeCoreAudio/AudioEngine.cpp)
#ifdef __APPLE__
                        sleep(1);
#else
                        Sleep(1);
#endif

and i've to include: 
#include &lt;unistd.h&gt;
#include &lt;string.h&gt;

to build that correctly.

**Comment by rmedaer** [comment]
This has been fixed in [AudioEngine.h](https://github.com/ZECTBynmo/node-core-audio/blob/develop/src/AudioEngine.h#L17-L20):

```
#ifdef __linux__
        #include <unistd.h>
        #include <string.h>
#endif
```

Have a good day,

**Comment by ZECTBynmo** [comment]
<3 thanks @rmedaer !
