### ISSUE TITLE
undefined symbol: Pa_Terminate Debian 8

### ISSUE THREAD

**Issue by YokiToki** [ZECTBynmo/node-core-audio#58]
Using nw.js respond following error:

    Uncaught Error: /home/tamat/sandbox/NwJS/spectrum analyzer/node_modules/node-core-audio/build/Release/NodeCoreAudio.node: undefined symbol: Pa_Terminate module.js:346 

This module is available for use in nw.js?

**Comment by rmedaer** [comment]
Hi @YokiToki ,

Could you try to launch node with `LD_PRELOAD` pointing to portaudio lib ? Something like:

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libportaudio.so node <your-script>.js
```

If it's working, it's a linking issue with node-gyp. FYI, I will refactor it in #61 ;-)

**Comment by YokiToki** [comment]
`LD_PRELOAD=/usr/local/lib/libportaudio.so node index.js`
works fine, thanks. But if I using node-core-audio in nw.js 
`cd /home/user/app/path
LD_PRELOAD=/usr/local/lib/libportaudio.so nw .`

`"Uncaught Error: /home/tamat/sandbox/NwJS/spectrum analyzer/node_modules/node-core-audio/build/Release/NodeCoreAudio.node: undefined symbol: _ZNK2v85Value9ToIntegerEv", source: module.js (346)`

**Comment by rmedaer** [comment]
Did you (re)build node-core-audio with nw-gyp ?

```
cd node_modules/node-core-audio
nw-gyp rebuild --target=<your-nwjs-version>
```

**Comment by rmedaer** [comment]
@YokiToki , can you confirm it's working with nwjs ? I tried this morning and it seems OK for me ..

**Comment by YokiToki** [comment]
I have another problem, so I can't confirm that it's fully working now. But that solved problem with "Pa_Terminate" error in node and nw.

**Comment by rmedaer** [comment]
Many thanks @YokiToki , the following commit cbfeb8e7e5fdb3d217c9db8adeda01a92a4578fc should fixed your issue without  using LD_PRELOAD.
