### ISSUE TITLE
Can't play wav sound using engine.write()

### ISSUE THREAD

**Issue by Cinetik** [ZECTBynmo/node-core-audio#60]
Hi,

I'm using this module to force play a sound from speakers and so far I can switch to output sources but my next step is to play a sound instead of redirect input to output.
Only I can't understand what I need to give the write function.
An array of what ? What format ? Why not directly a Buffer ?

**Comment by rmedaer** [comment]
Using buffer instead of array is a great idea ! ;-) As you already know, you can try Escaux' version while merging changes.

Cheers,
