### ISSUE TITLE
I can't install the module

### ISSUE THREAD

**Issue by NervenCid** [ZECTBynmo/node-core-audio#69]
Hello, i tried to install the module but i get this instead:

c:\users\nerve\appdata\roaming\npm\node_modules\node-core-audio\nodecoreaudio\AudioEngine.h(11): fatal er
ror C1083: Cannot open include file: 'node_internals.h': No such file or directory (compiling source file
 ..\NodeCoreAudio\AudioEngine.cpp) [C:\Users\nerve\AppData\Roaming\npm\node_modules\node-core-audio\build
\NodeCoreAudio.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\node-core-audio\nodecoreaudio\AudioEngine.h(11): fatal er
ror C1083: Cannot open include file: 'node_internals.h': No such file or directory (compiling source file
 ..\NodeCoreAudio\NodeCoreAudio.cpp) [C:\Users\nerve\AppData\Roaming\npm\node_modules\node-core-audio\bui
ld\NodeCoreAudio.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nerve\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\nerve\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\node-core-audio
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\nerve\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\nerve\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "node-core-audio"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! node-core-audio@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-core-audio@0.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-core-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-core-audio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-core-audio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1

How can i fix it?

**Comment by NateTheGreatt** [comment]
I'm having this issue as well, on different versions of node & node-gyp:
```
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.2.1
```

**Comment by spoggie** [comment]
same for me
`npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE`

Fehlermeldung: 

\appdata\roaming\npm\node_modules\node-core-audio\nodecoreaudio\AudioEngine.h(11): fatal error C1083: Cannot open include file: 'node_internals.h': No such f
ile or directory (compiling source file ..\NodeCoreAudio\AudioEngine.cpp)

**Comment by The-Oracle** [comment]
Try running: npm install ZECTBynmo/node-core-audio

Fixed it for me, it pulls from the Github project, where the bug has been fixed.

**Comment by spoggie** [comment]
Ok good to know. I will check that out.

**Comment by hugohil** [comment]
I just ran: `npm i ZECTBynmo/node-core-audio` with node `v4.4.4` on OS X 10.12 and it now works well for me too.

**Comment by NervenCid** [comment]
There are a more updated version of the package?

**Comment by ZECTBynmo** [comment]
Sorry for lack of attention in this repo. New contributors would be more than welcome. I just published a new package version that's up to date with the repository. Please let me know if that doesn't solve your issues.

**Comment by NervenCid** [comment]
@ZECTBynmo Thank so much you for the update
